# Nombre del workflow
name: Test WebFlix

# Ejecutar solo en push
on: push

# Variables de entorno necesarias para los tests
env:
  NODE_ENV: test
  PORT: 3000
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        PORT: 3000

    - name: Upload test coverage
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage/
